name: Sync Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # リポジトリAをチェックアウト
      - name: Checkout Repository A
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      # リポジトリBをクローン
      - name: Clone Repository B
        run: |
          git remote add repoB https://x-access-token:${{ secrets.A_REPO_PAT }}@github.com/buriki-test-org/ga_test_sync_private.git
          git remote -v
          git ls-remote repoB
