name: checkout private repository ( pat )

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          # プライベートリポジトリを指定
          repository: buriki-test-org/ga_test_sync_private
          # checkout 先のパスを指定
          path: ./ga_test_sync_private
          # Personal Access Token を指定
          token: ${{ secrets.A_REPO_PAT }}

      # プライベートリポジトリの中身を表示してみる
      - run: git push https://x-access-token:${{secrets.A_REPO_PAT}}@github.com/buriki-test-org/ga_test_sync_private.git --force
      #- run: ls ./ga_test_sync_private
